version: '2'
services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - "/db_data:/var/lib/postgresql/data"
    env_file: .env

  web:
    restart: always
    build: ./web
    ports:
      - "8000:8000"
    expose:
      - "8000"
    links:
      - postgres
    volumes:
     - ./web:/usr/src/app
     - ./web/static:/usr/src/app/static
    env_file: .env
    environment:
      DEBUG: 'true'
    command: gunicorn workr.wsgi -b 0.0.0.0:8000 --reload

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web
    depends_on:
      - web
